// Generated by CoffeeScript 1.4.0
(function() {
  var fs, publish, pubnub, _;

  fs = require("fs");

  pubnub = require("pubnub");

  _ = require("underscore");

  /*
   This module is accessible throught the command line, and allows for changes
   to be sent to any connected client to the pubnub hotfix_refresh channel
  */


  exports.require = ["celeri"];

  exports.plugin = function(celeri) {
    return celeri.option({
      command: "push-changes",
      description: "Pushes changes to all clients that are currently viewing the site",
      optional: {
        "config": "Configuration file for pubnub.",
        "critical": "Critical update - user account is force refreshed.",
        "message": "Message to display to the client.",
        "filter": "mongodb-style filter for each client"
      },
      defaults: {
        "config": "/usr/local/etc/hotfix/config.json",
        "critical": false,
        "message": "New updates are available for this page.",
        "messagePrefix": "This page needs to be refreshed"
      }
    }, publish);
  };

  publish = function(data) {
    var config, pubNubClient;
    if (data.filter) {
      data.filter = JSON.parse(data.filter);
    }
    console.log("refreshing all connected clients");
    config = require(data.config);
    pubNubClient = pubnub.init(config.pubnub);
    return pubNubClient.publish({
      channel: "hotfix_refresh",
      message: {
        critical: data.critical,
        text: (config.messagePrefix ? "" + config.messagePrefix + ": " : "") + data.message,
        filter: data.filter
      }
    });
  };

}).call(this);
