// Generated by CoffeeScript 1.4.0
(function() {
  var fs, pubnub, _;

  _ = require("underscore");

  fs = require("fs");

  pubnub = require("pubnub");

  /*
   This module is accessible throught the command line, and allows for changes
   to be sent to any connected client to the pubnub hotfix_refresh channel
  */


  exports.require = ["celeri", "pubsub.pubnub"];

  exports.plugin = function(celeri, pubnubClient, loader) {
    return celeri.option({
      command: "push-changes",
      description: "Pushes changes to all clients that are currently viewing the site",
      optional: {
        "config": "Configuration file for pubnub.",
        "critical": "Critical update - user account is force refreshed.",
        "message": "Message to display to the client.",
        "filter": "mongodb-style filter for each client"
      },
      defaults: {
        "critical": loader.params("data.critical") || false,
        "message": loader.params("data.message") || "New updates are available for this page."
      }
    }, function(data) {
      if (data.filter) {
        data.filter = JSON.parse(data.filter);
      }
      console.log("refreshing all connected clients");
      return pubnubClient.publish({
        channel: "hotfix_refresh",
        message: {
          critical: data.critical,
          text: data.message,
          filter: data.filter
        }
      });
    });
  };

}).call(this);
