// Generated by CoffeeScript 1.4.0
(function() {
  var fs, request, _;

  _ = require("underscore");

  fs = require("fs");

  request = require("request");

  /*
   This module is accessible throught the command line, and allows for changes
   to be sent to any connected client to the pubnub hotfix_refresh channel
  */


  exports.require = ["celeri"];

  exports.plugin = function(celeri, loader) {
    return celeri.option({
      command: "push OR push-changes",
      description: "Pushes changes to all clients that are currently viewing the site",
      optional: {
        config: "Configuration file for pubnub.",
        filter: "mongodb-style filter for each client",
        message: "Message to display to the client.",
        interval: "The interval in MS to randomize page refreshes",
        critical: "Critical update - user account is force refreshed.",
        gateway: "The hotfix gateway",
        key: "The hotfix host key"
      },
      defaults: _.extend({
        message: "New updates are available for this page.",
        interval: 1000 * 60,
        critical: false
      }, loader.params("data"))
    }, function(data) {
      if (data.filter) {
        data.filter = JSON.parse(data.filter);
      }
      console.log("refreshing all connected clients");
      return request.post({
        url: ("" + data.gateway + "/info.json?key=") + data.key,
        json: {
          message: data.message,
          interval: data.interval,
          critical: data.critical,
          filter: data.filter
        }
      }, function(e, r, b) {
        return console.log(b);
      });
    });
  };

}).call(this);
