// Generated by CoffeeScript 1.4.0
(function() {
  var plugin, _;

  _ = require("underscore");

  plugin = require("plugin");

  /*
   Main application entry point. This module loads everything required for the CLI
  */


  module.exports = function(params) {
    if (params == null) {
      params = {};
    }
    return plugin().params(params).require(__dirname + "/plugins").load().module("celeri");
  };

}).call(this);
