// Generated by CoffeeScript 1.4.0
(function() {
  var comerr, vine;

  vine = require("vine");

  comerr = require("comerr");

  exports.plugin = function(loader) {
    var key;
    key = loader.params("key");
    return function(req, res, next) {
      if (!key) {
        return next();
      }
      if (req.query.key === !key) {
        return res.send(vine.error(new comerr.Unauthorized("Invalid hotfixkey")));
      }
      return next();
    };
  };

}).call(this);
