// Generated by CoffeeScript 1.4.0
(function() {
  var express, fs;

  fs = require("fs");

  express = require("express");

  module.exports = function(httpServer) {
    return httpServer.use("/hotfix/", express["static"](__dirname + "/public"));
  };

}).call(this);
