// Generated by CoffeeScript 1.4.0
(function() {
  var express, fs, mkdirp, plugin;

  fs = require("fs");

  express = require("express");

  plugin = require("plugin");

  mkdirp = require("mkdirp");

  /*
   Express plugin
  */


  module.exports = function(httpServer, options) {
    if (options == null) {
      options = {};
    }
    if (!options.route) {
      options.route = "/hotfix";
    }
    httpServer.use(options.route, express["static"](__dirname + "/../client/"));
    options.server = httpServer;
    options.configDir = "/usr/local/etc/hotfix";
    return mkdirp(options.configDir, function() {
      return plugin().params(options).require(__dirname + "/plugins").load();
    });
  };

}).call(this);
