// Generated by CoffeeScript 1.4.0
(function() {

  module.exports = '\
  <div class="hotfix-notification">\
    <div class="hotfix-message"></div> \
    <div class="hotfix-buttons">\
      <a class="hotfix-ignore-button">ignore</a> \
      <a class="hotfix-refresh-button">refresh</a>\
    </div>\
  </div>\
';

}).call(this);
