// Generated by CoffeeScript 1.4.0
(function() {
  var celeri;

  celeri = require("celeri");

  /*
   Celeri module is returned here to keep things a bit more uniform
  */


  exports.plugin = function() {
    return celeri;
  };

}).call(this);
