// Generated by CoffeeScript 1.4.0
(function() {
  var express, fs, mkdirp, outcome, vine;

  mkdirp = require("mkdirp");

  express = require("express");

  fs = require("fs");

  vine = require("vine");

  outcome = require("outcome");

  exports.require = ["auth.middleware"];

  exports.plugin = function(authMiddleware, loader) {
    var configDir, infoPath, server;
    server = loader.params("server");
    configDir = loader.params("configDir");
    infoPath = "" + configDir + "/info.json";
    /*
    */

    server.get("/hotfix/info.json", function(req, res) {
      var o;
      o = outcome.e(function(err) {
        return res.send(vine.error(err));
      });
      return fs.readFile(infoPath, "utf8", o.s(function(content) {
        var json;
        json = JSON.parse(content);
        return res.jsonp(vine.result(json));
      }));
    });
    /*
    */

    return server.post("/hotfix/info.json", express.bodyParser(), authMiddleware, function(req, res) {
      var info, o;
      info = req.body;
      info.updatedAt = Date.now();
      o = outcome.e(function(err) {
        return res.send(vine.error(err));
      });
      return fs.writeFile(infoPath, JSON.stringify(info, null, 2), o.s(function() {
        return res.send(vine.result(info));
      }));
    });
  };

}).call(this);
