// Generated by CoffeeScript 1.4.0
(function() {
  var pubnub;

  pubnub = require("pubnub");

  /*
    Initializes the pubnub client
  */


  exports.plugin = function(loader) {
    return pubnub.init(loader.params("pubnub"));
  };

}).call(this);
