// Generated by CoffeeScript 1.4.0
(function() {
  var express, hotfix, runServer;

  hotfix = require("../../../");

  express = require("express");

  /*
   Runs a stand-alone http server
  */


  exports.require = ["celeri"];

  exports.plugin = function(celeri, loader) {
    return celeri.option({
      command: "server",
      description: "Runs the hotfix http server",
      optional: {
        port: "The http port to run hotfix on"
      },
      defaults: {
        port: loader.params("data.port") || 8080
      }
    }, runServer);
  };

  /*
  */


  runServer = function(data) {
    var server;
    server = express();
    hotfix.server(server);
    return server.listen(data.port);
  };

}).call(this);
